let a =new Date;
console.log(a.getDate());
console.log(a.getMonth()+1);
console.log(a);
console.log(a.getTime());
console.log(a.getFullYear());
let date = a.getDate()+'-'+(a.getMonth()+1) +'-'+a.getFullYear();
console.log(date);
let num=12.2212;
console.log(Math.floor(num));
console.log(Math.ceil(num));
console.log(Math.round(num));
console.log(Math.sqrt(4));